<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="LamSims.Core.Catalogs" />
    <Using Include="LamSims.Core.Queueing" />
    <Using Include="LamSims.Core.Scanning" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LamSims.App\LamSims.App.csproj" />
    <ProjectReference Include="..\LamSims.Core\LamSims.Core.csproj" />
  </ItemGroup>

</Project>
